# output paths for hydra logs
run:
  # dir: logs/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  dir: logs/${exp_name}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
sweep:
  dir: logs/${exp_name}/multiruns/${now:%Y-%m-%d_%H-%M-%S}
  subdir: ${hydra.job.num}

# you can set here environment variables that are universal for all users
# for system specific variables (like data paths) it's better to use .env file!
# job:
#   env_set:
#     EXAMPLE_VAR: "example_value"
