_target_: src.models.debiaser.Debiaser

model_name: 'distilbert-base-uncased'
embedding_layer: 'last'
debias_mode: 'sentence'

learning_rate: 5e-5
weight_decay: 0.0
adam_eps: 1e-8
warmup_steps: 0

loss_alpha: 0.2
loss_beta: 0.8
