_target_: src.models.debias.Debiaser

model_name: 'distilbert-base-uncased'
embedding_layer: 'last'
debias_mode: 'sentence'
batch_size: 32
data_dir: ${data_dir}

learning_rate: 5e-5
weight_decay: 0.0
adam_eps: 1e-8
warmup_steps: 0

loss_alpha: 0.2
loss_beta: 0.8

seat_data:
    SEAT6: ${data_dir}/sent-weat6.jsonl
    SEAT7: ${data_dir}/sent-weat7.jsonl
    SEAT8: ${data_dir}/sent-weat8.jsonl

news_data_url: 'http://data.statmt.org/news-commentary/v15/training-monolingual/news-commentary-v15.en.gz'

# Files with attribute lists
female_attributes_filepath: ${data_dir}/female.txt
male_attributes_filepath: ${data_dir}/male.txt
stereotypes_filepath: ${data_dir}/stereotype.txt

# Filename to cache data at
cached_data_path: ${data_dir}/data.pickle
