_target_: src.models.mlm_debias.MLMDebias

model_name: 'distilbert-base-uncased'
embedding_layer: 'last'
batch_size: 4  # TODO
data_dir: ${data_dir}

learning_rate: 5e-5
weight_decay: 0.0
adam_eps: 1e-8
warmup_steps: 0

loss_alpha: 0.2
loss_beta: 0.8

seat_data:
    SEAT6: '/home/przm/bs/data/sent-weat6.jsonl'
    SEAT7: '/home/przm/bs/data/sent-weat7.jsonl'
    SEAT8: '/home/przm/bs/data/sent-weat8.jsonl'



news_data_url: 'http://data.statmt.org/news-commentary/v15/training-monolingual/news-commentary-v15.en.gz'

# Files with attribute lists
female_attributes_filepath: 'data/female.txt'
male_attributes_filepath: 'data/male.txt'
stereotypes_filepath: 'data/stereotype.txt'

# Filename to cache data at
cached_data: 'attributes_dataset.obj'
