lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: step

checkpoint_callback:
  _target_: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
  dirpath: 'checkpoints/'