lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: step

checkpoint_callback:
  _target_: src.callbacks.model_checkpoint.ModelCheckpointWithHuggingface
  dirpath: 'checkpoints/'