_target_: src.datamodules.debias_datamodule.DebiasDataModule

model_name: ${model.model_name}
batch_size: 128
data_dir: ${data_dir}

datafiles:
    plaintext: 'http://data.statmt.org/news-commentary/v15/training-monolingual/news-commentary-v15.en.gz'
    attributes_female: 'https://raw.githubusercontent.com/kanekomasahiro/context-debias/main/data/female.txt'
    attributes_male: 'https://raw.githubusercontent.com/kanekomasahiro/context-debias/main/data/male.txt'
    targets_stereotypes: 'https://raw.githubusercontent.com/kanekomasahiro/context-debias/main/data/stereotype.txt'
    SEAT6: 'https://raw.githubusercontent.com/W4ngatang/sent-bias/master/tests/sent-weat6.jsonl'
    SEAT7: 'https://raw.githubusercontent.com/W4ngatang/sent-bias/master/tests/sent-weat7.jsonl'
    SEAT8: 'https://raw.githubusercontent.com/W4ngatang/sent-bias/master/tests/sent-weat8.jsonl'

seat_data:
    SEAT6: ${data_dir}/sent-weat6.jsonl
    SEAT7: ${data_dir}/sent-weat7.jsonl
    SEAT8: ${data_dir}/sent-weat8.jsonl

seed: ${seed}
num_proc: 32
num_workers: 16
